config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "trains#index"
  resources :users, only: [:edit, :update]
  resources :trains, only: [:new, :create, :destroy] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/train.rb
class Train < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :trainname, class_name: 'TrainName'
  has_many :train_users, dependent: :destroy
  has_many :users, through: :train_users
  has_many :messages, dependent: :destroy
  #選択が「---」の時は保存できないようにする
  validates :trainname_id, numericality: { other_than: 1 , message: "can't be blank"}
end

app/models/train_name.rb
class TrainName < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' , active: false}, { id: 2, name: 'JR東海道新幹線' }, { id: 3, name: 'JR横須賀線' },
    { id: 4, name: 'JR横浜線' }, { id: 5, name: 'JR京浜東北線' }, { id: 6, name: 'JR京葉線' },
    { id: 7, name: 'JR五日市線' }, { id: 8, name: 'JR埼京線' }, { id: 9, name: 'JR山手線' },
    { id: 10, name: 'JR上越新幹線' }, { id: 11, name: 'JR常磐線' }, { id: 12, name: 'JR青梅線' },
    { id: 13, name: 'JR総武本線(東京-銚子)' }, { id: 14, name: 'JR総武線各停(御茶ノ水-錦糸町)' },
    { id: 15, name: 'JR中央本線(東京-塩尻)' }, { id: 16, name: 'JR北陸新幹線(長野経由)' },
    { id: 17, name: 'JR東海道本線(東京-熱海)' }, { id: 18, name: 'JR東北新幹線' },
    { id: 19, name: 'JR宇都宮線〔東北本線〕・JR上野東京ライン' }, { id: 20, name: 'JR南武線(川崎-立川)' },
    { id: 21, name: 'JR八高線(八王子-高麗川)' }, { id: 22, name: 'JR武蔵野線(府中本町-南船橋)' },
    { id: 23, name: 'ゆりかもめ' }, { id: 24, name: '京王井の頭線' }, { id: 25, name: '京王線' },
    { id: 26, name: '京王競馬場線' }, { id: 27, name: '京王高尾線' }, { id: 28, name: '京王新線' },
    { id: 29, name: '京王相模原線' }, { id: 30, name: '京王動物園線' }, { id: 31, name: '京成押上線' },
    { id: 32, name: '京成金町線' }, { id: 33, name: '京成本線' }, { id: 34, name: '京急空港線' },
    { id: 35, name: '京急本線' }, { id: 36, name: '小田急小田原線' }, { id: 37, name: '小田急多摩線' },
    { id: 38, name: '西武園線' }, { id: 39, name: '西武国分寺線' }, { id: 40, name: '西武山口線' },
    { id: 41, name: '西武新宿線' }, { id: 42, name: '西武多摩湖線(国分寺-萩山)' },
    { id: 43, name: '西武多摩湖線(萩山-多摩湖)' }, { id: 44, name: '西武多摩川線' }, { id: 45, name: '西武池袋線' },
    { id: 46, name: '西武拝島線' }, { id: 47, name: '西武豊島線' }, { id: 48, name: '西武有楽町線' },
    { id: 49, name: '多摩都市モノレール線' }, { id: 50, name: '東京メトロ丸ノ内線' },
    { id: 51, name: '東京メトロ丸ノ内線(中野坂上-方南町)' }, { id: 52, name: '東京メトロ銀座線' },
    { id: 53, name: '東京メトロ千代田線' }, { id: 54, name: '東京メトロ千代田線(綾瀬-北綾瀬)' },
    { id: 55, name: '東京メトロ東西線' }, { id: 56, name: '東京メトロ南北線' }, { id: 57, name: '東京メトロ日比谷線' },
    { id: 58, name: '東京メトロ半蔵門線' }, { id: 59, name: '東京メトロ有楽町線' },
    { id: 60, name: '東京メトロ副都心線' }, { id: 61, name: '東京モノレール' }, { id: 62, name: '東急世田谷線' },
    { id: 63, name: '東急大井町線' }, { id: 64, name: '東急池上線' }, { id: 65, name: '東急田園都市線' },
    { id: 66, name: '東急東横線' }, { id: 67, name: '東急目黒線' }, { id: 68, name: '都営大江戸線(環状部)' },
    { id: 69, name: '都営三田線' }, { id: 70, name: '都営新宿線' }, { id: 71, name: '都営浅草線' },
    { id: 72, name: '都電荒川線' }, { id: 73, name: 'りんかい線' }, { id: 74, name: '東武伊勢崎線〔スカイツリーライン〕' },
    { id: 75, name: '東武亀戸線' }, { id: 76, name: '東武大師線' }, { id: 77, name: '東武東上線' },
    { id: 78, name: '京成成田空港線・北総鉄道線' }, { id: 79, name: '東急多摩川線' }, { id: 80, name: '埼玉高速鉄道線' },
    { id: 81, name: 'JR湘南新宿ライン' }, { id: 82, name: 'JR横須賀武蔵野連絡線' },
    { id: 83, name: '東武伊勢崎線〔スカイツリーライン〕(押上-曳舟)' },
    { id: 84, name: '都営大江戸線(放射部)' }, { id: 85, name: 'つくばエクスプレス' },
    { id: 86, name: '千代田有楽町連絡線' }, { id: 87, name: '都営日暮里・舎人ライナー' },
    { id: 88, name: '御岳登山ケーブル' }, { id: 89, name: '高尾登山ケーブル' }
  ]

  include ActiveHash::Associations
  has_many :trains
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :train_users
  has_many :trains, through: :train_users
  has_many :messages

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  def index
    @trains = Train.order("trainname ASC")
  end

  def new
    @train = Train.new
  end

  def create
    @train = Train.new(train_params)
    if @train.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    train = Train.find(params[:id])
    train.destroy
    redirect_to root_path
  end

  private

  def train_params
    params.require(:train).permit(:trainname_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def edit
  end

  def show
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render:edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trainstatus</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <%# ログインしているときは以下を表示する %>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: :nav__logout %>
              <%= link_to "New Train", new_train_path, class: :nav__btn %>
            </div>
          <%# ログインしていないときは以下を表示する %>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © TRAIN STATUS All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/trains/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
      <div class="greeting">
        <p>こんにちは、<%= link_to current_user.name, user_path(current_user), class: :greeting__link %>さん</p>
      </div>
    <% end %>
    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
    <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
      
    </div>
  </div>
</main>

app/views/trains/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットグループ</h1>
  <%=form_with model: @train, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class="weight-bold-text">
       路線名を選択してください
        <span class="indispensable">(※必須)</span>
      </div>
      <%= f.collection_select(:trainname_id, TrainName.all, :id, :name, {}, {class:"select-box", id:"train-name"}) %>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <%= f.submit class: 'chat-room-form__action-btn'%>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, data: {turbo_method: :delete}, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>